# Autogenerated wrapper script for MPSolve_jll for aarch64-linux-gnu-cxx03
export libmps

using GMP_jll
JLLWrappers.@generate_wrapper_header("MPSolve")
JLLWrappers.@declare_library_product(libmps, "libmps.so.3")
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll)
    JLLWrappers.@init_library_product(
        libmps,
        "lib/libmps.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
